// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transit.Data;

namespace Transit.Migrations
{
    [DbContext(typeof(TransitDataContext))]
    [Migration("20240718021134_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Transit.Models.RouteSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("StopNumber")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Timepoint")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StopNumber");

                    b.ToTable("RouteSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            StopNumber = (short)6041,
                            Timepoint = (short)600
                        },
                        new
                        {
                            Id = 2L,
                            StopNumber = (short)6138,
                            Timepoint = (short)610
                        },
                        new
                        {
                            Id = 3L,
                            StopNumber = (short)6021,
                            Timepoint = (short)620
                        },
                        new
                        {
                            Id = 4L,
                            StopNumber = (short)6139,
                            Timepoint = (short)630
                        },
                        new
                        {
                            Id = 5L,
                            StopNumber = (short)6140,
                            Timepoint = (short)640
                        },
                        new
                        {
                            Id = 6L,
                            StopNumber = (short)9638,
                            Timepoint = (short)650
                        },
                        new
                        {
                            Id = 7L,
                            StopNumber = (short)6142,
                            Timepoint = (short)700
                        },
                        new
                        {
                            Id = 8L,
                            StopNumber = (short)6143,
                            Timepoint = (short)710
                        },
                        new
                        {
                            Id = 9L,
                            StopNumber = (short)6144,
                            Timepoint = (short)720
                        },
                        new
                        {
                            Id = 10L,
                            StopNumber = (short)6145,
                            Timepoint = (short)730
                        },
                        new
                        {
                            Id = 11L,
                            StopNumber = (short)6146,
                            Timepoint = (short)740
                        },
                        new
                        {
                            Id = 12L,
                            StopNumber = (short)6147,
                            Timepoint = (short)750
                        },
                        new
                        {
                            Id = 13L,
                            StopNumber = (short)6148,
                            Timepoint = (short)800
                        },
                        new
                        {
                            Id = 14L,
                            StopNumber = (short)6149,
                            Timepoint = (short)810
                        },
                        new
                        {
                            Id = 15L,
                            StopNumber = (short)6150,
                            Timepoint = (short)820
                        },
                        new
                        {
                            Id = 16L,
                            StopNumber = (short)6151,
                            Timepoint = (short)830
                        },
                        new
                        {
                            Id = 17L,
                            StopNumber = (short)6216,
                            Timepoint = (short)840
                        },
                        new
                        {
                            Id = 18L,
                            StopNumber = (short)6152,
                            Timepoint = (short)850
                        },
                        new
                        {
                            Id = 19L,
                            StopNumber = (short)6040,
                            Timepoint = (short)900
                        },
                        new
                        {
                            Id = 20L,
                            StopNumber = (short)6119,
                            Timepoint = (short)910
                        },
                        new
                        {
                            Id = 21L,
                            StopNumber = (short)6120,
                            Timepoint = (short)920
                        },
                        new
                        {
                            Id = 22L,
                            StopNumber = (short)6121,
                            Timepoint = (short)930
                        },
                        new
                        {
                            Id = 23L,
                            StopNumber = (short)6122,
                            Timepoint = (short)940
                        },
                        new
                        {
                            Id = 24L,
                            StopNumber = (short)6123,
                            Timepoint = (short)950
                        },
                        new
                        {
                            Id = 25L,
                            StopNumber = (short)6124,
                            Timepoint = (short)1000
                        },
                        new
                        {
                            Id = 26L,
                            StopNumber = (short)6125,
                            Timepoint = (short)1010
                        },
                        new
                        {
                            Id = 27L,
                            StopNumber = (short)6126,
                            Timepoint = (short)1020
                        },
                        new
                        {
                            Id = 28L,
                            StopNumber = (short)6127,
                            Timepoint = (short)1030
                        },
                        new
                        {
                            Id = 29L,
                            StopNumber = (short)6128,
                            Timepoint = (short)1040
                        },
                        new
                        {
                            Id = 30L,
                            StopNumber = (short)6129,
                            Timepoint = (short)1050
                        },
                        new
                        {
                            Id = 31L,
                            StopNumber = (short)6130,
                            Timepoint = (short)1100
                        },
                        new
                        {
                            Id = 32L,
                            StopNumber = (short)6132,
                            Timepoint = (short)1110
                        },
                        new
                        {
                            Id = 33L,
                            StopNumber = (short)6133,
                            Timepoint = (short)1120
                        },
                        new
                        {
                            Id = 34L,
                            StopNumber = (short)6135,
                            Timepoint = (short)1130
                        },
                        new
                        {
                            Id = 35L,
                            StopNumber = (short)6136,
                            Timepoint = (short)1140
                        },
                        new
                        {
                            Id = 36L,
                            StopNumber = (short)6137,
                            Timepoint = (short)1150
                        },
                        new
                        {
                            Id = 37L,
                            StopNumber = (short)6041,
                            Timepoint = (short)1200
                        },
                        new
                        {
                            Id = 38L,
                            StopNumber = (short)6138,
                            Timepoint = (short)1210
                        },
                        new
                        {
                            Id = 39L,
                            StopNumber = (short)6021,
                            Timepoint = (short)1220
                        },
                        new
                        {
                            Id = 40L,
                            StopNumber = (short)6139,
                            Timepoint = (short)1230
                        },
                        new
                        {
                            Id = 41L,
                            StopNumber = (short)6140,
                            Timepoint = (short)1240
                        },
                        new
                        {
                            Id = 42L,
                            StopNumber = (short)9638,
                            Timepoint = (short)1250
                        },
                        new
                        {
                            Id = 43L,
                            StopNumber = (short)6142,
                            Timepoint = (short)1300
                        },
                        new
                        {
                            Id = 44L,
                            StopNumber = (short)6143,
                            Timepoint = (short)1310
                        },
                        new
                        {
                            Id = 45L,
                            StopNumber = (short)6144,
                            Timepoint = (short)1320
                        },
                        new
                        {
                            Id = 46L,
                            StopNumber = (short)6145,
                            Timepoint = (short)1330
                        },
                        new
                        {
                            Id = 47L,
                            StopNumber = (short)6146,
                            Timepoint = (short)1340
                        },
                        new
                        {
                            Id = 48L,
                            StopNumber = (short)6147,
                            Timepoint = (short)1350
                        },
                        new
                        {
                            Id = 49L,
                            StopNumber = (short)6148,
                            Timepoint = (short)1400
                        },
                        new
                        {
                            Id = 50L,
                            StopNumber = (short)6149,
                            Timepoint = (short)1410
                        },
                        new
                        {
                            Id = 51L,
                            StopNumber = (short)6150,
                            Timepoint = (short)1420
                        },
                        new
                        {
                            Id = 52L,
                            StopNumber = (short)6151,
                            Timepoint = (short)1430
                        },
                        new
                        {
                            Id = 53L,
                            StopNumber = (short)6216,
                            Timepoint = (short)1440
                        },
                        new
                        {
                            Id = 54L,
                            StopNumber = (short)6152,
                            Timepoint = (short)1450
                        },
                        new
                        {
                            Id = 55L,
                            StopNumber = (short)6040,
                            Timepoint = (short)1500
                        },
                        new
                        {
                            Id = 56L,
                            StopNumber = (short)6119,
                            Timepoint = (short)1510
                        },
                        new
                        {
                            Id = 57L,
                            StopNumber = (short)6120,
                            Timepoint = (short)1520
                        },
                        new
                        {
                            Id = 58L,
                            StopNumber = (short)6121,
                            Timepoint = (short)1530
                        },
                        new
                        {
                            Id = 59L,
                            StopNumber = (short)6122,
                            Timepoint = (short)1540
                        },
                        new
                        {
                            Id = 60L,
                            StopNumber = (short)6123,
                            Timepoint = (short)1550
                        },
                        new
                        {
                            Id = 61L,
                            StopNumber = (short)6124,
                            Timepoint = (short)1600
                        },
                        new
                        {
                            Id = 62L,
                            StopNumber = (short)6125,
                            Timepoint = (short)1610
                        },
                        new
                        {
                            Id = 63L,
                            StopNumber = (short)6126,
                            Timepoint = (short)1620
                        },
                        new
                        {
                            Id = 64L,
                            StopNumber = (short)6127,
                            Timepoint = (short)1630
                        },
                        new
                        {
                            Id = 65L,
                            StopNumber = (short)6128,
                            Timepoint = (short)1640
                        },
                        new
                        {
                            Id = 66L,
                            StopNumber = (short)6129,
                            Timepoint = (short)1650
                        },
                        new
                        {
                            Id = 67L,
                            StopNumber = (short)6130,
                            Timepoint = (short)1700
                        },
                        new
                        {
                            Id = 68L,
                            StopNumber = (short)6132,
                            Timepoint = (short)1710
                        },
                        new
                        {
                            Id = 69L,
                            StopNumber = (short)6133,
                            Timepoint = (short)1720
                        },
                        new
                        {
                            Id = 70L,
                            StopNumber = (short)6135,
                            Timepoint = (short)1730
                        },
                        new
                        {
                            Id = 71L,
                            StopNumber = (short)6136,
                            Timepoint = (short)1740
                        },
                        new
                        {
                            Id = 72L,
                            StopNumber = (short)6137,
                            Timepoint = (short)1750
                        },
                        new
                        {
                            Id = 73L,
                            StopNumber = (short)6041,
                            Timepoint = (short)1800
                        },
                        new
                        {
                            Id = 74L,
                            StopNumber = (short)6138,
                            Timepoint = (short)1810
                        },
                        new
                        {
                            Id = 75L,
                            StopNumber = (short)6021,
                            Timepoint = (short)1820
                        },
                        new
                        {
                            Id = 76L,
                            StopNumber = (short)6139,
                            Timepoint = (short)1830
                        },
                        new
                        {
                            Id = 77L,
                            StopNumber = (short)6140,
                            Timepoint = (short)1840
                        },
                        new
                        {
                            Id = 78L,
                            StopNumber = (short)9638,
                            Timepoint = (short)1850
                        },
                        new
                        {
                            Id = 79L,
                            StopNumber = (short)6142,
                            Timepoint = (short)1900
                        },
                        new
                        {
                            Id = 80L,
                            StopNumber = (short)6143,
                            Timepoint = (short)1910
                        },
                        new
                        {
                            Id = 81L,
                            StopNumber = (short)6144,
                            Timepoint = (short)1920
                        },
                        new
                        {
                            Id = 82L,
                            StopNumber = (short)6145,
                            Timepoint = (short)1930
                        },
                        new
                        {
                            Id = 83L,
                            StopNumber = (short)6146,
                            Timepoint = (short)1940
                        },
                        new
                        {
                            Id = 84L,
                            StopNumber = (short)6147,
                            Timepoint = (short)1950
                        },
                        new
                        {
                            Id = 85L,
                            StopNumber = (short)6148,
                            Timepoint = (short)2000
                        },
                        new
                        {
                            Id = 86L,
                            StopNumber = (short)6149,
                            Timepoint = (short)2010
                        },
                        new
                        {
                            Id = 87L,
                            StopNumber = (short)6150,
                            Timepoint = (short)2020
                        },
                        new
                        {
                            Id = 88L,
                            StopNumber = (short)6151,
                            Timepoint = (short)2030
                        },
                        new
                        {
                            Id = 89L,
                            StopNumber = (short)6216,
                            Timepoint = (short)2040
                        },
                        new
                        {
                            Id = 90L,
                            StopNumber = (short)6152,
                            Timepoint = (short)2050
                        });
                });

            modelBuilder.Entity("Transit.Models.RouteStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("RouteStops");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Beaudry Ave & 3rd St",
                            Number = (short)6041,
                            Order = (short)1
                        },
                        new
                        {
                            Id = 2L,
                            Name = "4th St & Figueroa St",
                            Number = (short)6138,
                            Order = (short)2
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Flower St & 5th St",
                            Number = (short)6021,
                            Order = (short)3
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Flower St & 7th St",
                            Number = (short)6139,
                            Order = (short)4
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Flower St & 8th St",
                            Number = (short)6140,
                            Order = (short)5
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Flower St & 9th St",
                            Number = (short)9638,
                            Order = (short)6
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Flower St & Olympic Blvd",
                            Number = (short)6142,
                            Order = (short)7
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Figueroa & 12th St (Crypto.com Arena)",
                            Number = (short)6143,
                            Order = (short)8
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Figueroa St & Pico Blvd",
                            Number = (short)6144,
                            Order = (short)9
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Figueroa St & Venice Blvd",
                            Number = (short)6145,
                            Order = (short)10
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Figueroa St & Washington Blvd",
                            Number = (short)6146,
                            Order = (short)11
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Figueroa St & 23rd St",
                            Number = (short)6147,
                            Order = (short)12
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Figueroa St & Adams Blvd",
                            Number = (short)6148,
                            Order = (short)13
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Figueroa St & 30th St",
                            Number = (short)6149,
                            Order = (short)14
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Figueroa St & Jefferson Blvd",
                            Number = (short)6150,
                            Order = (short)15
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Figueroa St & McCarthy Way",
                            Number = (short)6151,
                            Order = (short)16
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Exposition Blvd & Trousdale Pkwy",
                            Number = (short)6216,
                            Order = (short)17
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Exposition Blvd & Watt Way",
                            Number = (short)6152,
                            Order = (short)18
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Vermont Ave & Exposition Blvd",
                            Number = (short)6040,
                            Order = (short)19
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Vermont Ave & 37th Pl",
                            Number = (short)6119,
                            Order = (short)20
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Vermont Ave & 36th Pl",
                            Number = (short)6120,
                            Order = (short)21
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Jefferson Blvd & Vermont Ave",
                            Number = (short)6121,
                            Order = (short)22
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Jefferson Blvd & McClintock Ave",
                            Number = (short)6122,
                            Order = (short)23
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Jefferson Blvd & Hoover St",
                            Number = (short)6123,
                            Order = (short)24
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Figueroa St & 33rd St",
                            Number = (short)6124,
                            Order = (short)25
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Figueroa St & 30th St",
                            Number = (short)6125,
                            Order = (short)26
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Figueroa St & Adams Blvd",
                            Number = (short)6126,
                            Order = (short)27
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Figueroa St & 23rd St",
                            Number = (short)6127,
                            Order = (short)28
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Figueroa St & Washington Blvd",
                            Number = (short)6128,
                            Order = (short)29
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Figueroa St & Venice Blvd",
                            Number = (short)6129,
                            Order = (short)30
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Figueroa St & 12th St",
                            Number = (short)6130,
                            Order = (short)31
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Figueroa & 11th St (Crypto.com Arena)",
                            Number = (short)6132,
                            Order = (short)32
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Figueroa St & Olympic Blvd",
                            Number = (short)6133,
                            Order = (short)33
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Figueroa St & 8th St",
                            Number = (short)6135,
                            Order = (short)34
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Figueroa St & 7th St",
                            Number = (short)6136,
                            Order = (short)35
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Figueroa St & 5th St",
                            Number = (short)6137,
                            Order = (short)36
                        });
                });

            modelBuilder.Entity("Transit.Models.RouteSchedule", b =>
                {
                    b.HasOne("Transit.Models.RouteStop", "RouteStop")
                        .WithMany("RouteSchedules")
                        .HasForeignKey("StopNumber")
                        .HasPrincipalKey("Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("Transit.Models.RouteStop", b =>
                {
                    b.Navigation("RouteSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
